disabled_rules:
  - mark
  - inclusive_language
  - nesting

opt_in_rules:
  - attributes
  - empty_count
  - file_header
  - fatal_error_message
  - private_outlet
  - raw_value_for_camel_cased_codable_enum

excluded:
  - bin
  - Carthage
  - fastlane
  - lib
  - script
  - .bundle
  - xcsharedata

# Be mindful of force cast force try. Add lint ignoring commentary if these are valid.
force_cast:
  severity: warning
force_try:
  severity: warning

# Personal preference.
line_length:
  warning: 150
  error: 500
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length: 2
  max_length:
    warning: 90
    error: 1000
  excluded:
    - id
    - x
    - y

# Prefer file lengths of less than 500. Its a code smell otherwise.
file_length:
  warning: 500
  error: 1200

type_body_length:
  warning: 500
  error: 1200

function_body_length:
  warning: 80
  error: 120

attributes:
  always_on_same_line: ["@IBAction", "@NSManaged", "@Environment"]
  always_on_line_above: ["@Parameter", "@Test"]

reporter: "xcode"
