import Foundation
import Testing
@testable import JWWCore

final class DecodingErrorDebugExtensionTests {
    /// Validate we properly parse out a `.dataCorrupted` error generated by invalid JSON.
    @Test
    func testReportingInvalidJSONError() throws {
        let json = """
        {
            "first_name": "Steve",
            "last_name": Case",
            "age": 64
        }
        """
        let expectedMessage = "Data corrupted. The given data was not valid JSON. Unexpected character 'C' around line 3, column 18."

        try assertDecodingErrorMessageEquals(json, expectedMessage)
    }

    /// Validate we properly parse out a `.keyNotFound` error.
    @Test
    func testReportingMissingKeyJSONErrorWithEmptyPath() throws {
        let json = """
        {
            "first_name": "Steve",
            "age": 64
        }
        """
        let expectedMessage = "Key not found: 'last_name'."

        try assertDecodingErrorMessageEquals(json, expectedMessage)
    }

    /// Validate we properly parse out a `.typeMismatch` error.
    @Test
    func testTypeMismatchError() throws {
        let json = """
        {
            "first_name": "Steve",
            "last_name": "Case",
            "age": "64"
        }
        """

        let expectedMessage = "Type mismatch. Expected to decode Int but found a string instead. key path: age"

        try assertDecodingErrorMessageEquals(json, expectedMessage)
    }

    /// Validate we properly parse out a `.valueNotFound` error.
    @Test
    func testValueNotFoundError() throws {
        let json = """
        {
            "first_name": "Steve",
            "last_name": null,
            "age": 64
        }
        """

        let expectedMessage = "Value not found at 'last_name'. Cannot get value of type String -- found null value instead"

        try assertDecodingErrorMessageEquals(json, expectedMessage)
    }

    // MARK: Private / Convenience
    // ====================================
    // Private / Convenience
    // ====================================

    private func assertDecodingErrorMessageEquals(_ json: String, _ expectedMessage: String, file: String = #filePath, line: Int = #line) throws {
        let data = try #require(json.data(using: .utf8))

        #expect {
            try JSONDecoder().decode(CodableFixture.self, from: data)
        } throws: { error in
            let isDecodingError = error is DecodingError
            let descriptionMatches = String(reflecting: error) == expectedMessage
            return isDecodingError && descriptionMatches
        }
    }
}

/// Fixture that can be used for stubbing in payloads for various testing purposes.
private struct CodableFixture: Codable {
    let firstName: String
    let lastName: String
    let age: Int

    enum CodingKeys: String, CodingKey {
        case firstName = "first_name"
        case lastName = "last_name"
        case age
    }

    static func fixture() -> CodableFixture {
        return CodableFixture(firstName: "Steve", lastName: "Case", age: 60)
    }
}

private struct People: Codable {
    let people: [CodableFixture]
}
