name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  test:
    name: "Unit Tests"
    runs-on: macos-12
    env:
      XCODE_SCHEME: "JWWCore"
      # DEVELOPER_DIR: "/Applications/Xcode_13.4.1.app/Contents/Developer"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Test (macOS)
        run: |
          set -o pipefail && env NSUnbufferedIO=YES
          xcodebuild build-for-testing -usePackageSupportBuiltinSCM -scheme "$XCODE_SCHEME" -destination "platform=macOS" | xcpretty

      - name: Build and Test (iOS)
        run: |
          set -o pipefail && env NSUnbufferedIO=YES
          xcodebuild build-for-testing -usePackageSupportBuiltinSCM -scheme "$XCODE_SCHEME" -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty

      - name: Build and Test (Mac Catalyst)
        run: |
          set -o pipefail && env NSUnbufferedIO=YES
          xcodebuild build-for-testing -usePackageSupportBuiltinSCM -scheme "$XCODE_SCHEME" -destination "platform=macOS,variant=Mac Catalyst" | xcpretty
